### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by jinyuanchun** [aristoteleo/spateo-release#141]
i use `pip install spateo-release`， according to document. but failed 

![image](https://user-images.githubusercontent.com/40689145/185047865-eaf18faf-fca6-4374-bac5-65be1c2c3eb7.png)

**Comment by Yao-14** [comment]
please use this method to download spateo temporarily:
**pip install git+https://github.com/aristoteleo/spateo-release**

**Comment by jinyuanchun** [comment]
ok
