### ISSUE TITLE
typing error

### ISSUE THREAD

**Issue by jinyuanchun** [aristoteleo/spateo-release#142]
i intall successly , but when i use it , some error . the  reason is   typing.Literal is only available from Python 3.8 and up. update the document

![image](https://user-images.githubusercontent.com/40689145/185070216-e91a9436-7aac-454e-a2e9-7b0ccc941dee.png)

**Comment by Yao-14** [comment]
Hi **@jinyuanchun**,
Yes, we recommend Python 3.8 and above. But this problem I can solve today, let you in python3.7 can also use spateo. Please download the latest version of spateo at a later date.

**Comment by jinyuanchun** [comment]
ok

**Comment by Yao-14** [comment]
Hi @**jinyuanchun**,
Now you can try again to use spateo in python3.7

**Comment by jinyuanchun** [comment]
> Hi @**jinyuanchun**, Now you can try again to use spateo in python3.7

ok, thank u, i will try later
