### ISSUE TITLE
Problem about dataset loading

### ISSUE THREAD

**Issue by Zhixuan-Jing** [aristoteleo/spateo-release#151]
When I was about to run the test code which is downloaded from spateo website, the function st.io.read_bgi_agg could not work normally, and the error **gzip.BadGzipFile: Not a gzipped file (b'Pa')** occured. I use WSL Ubuntu 20.04 and install spateo following the installation guidance. Do you have any idea about that?

**Comment by Yao-14** [comment]
Hi @Zhixuan-Jing ,
Thank you so much for your question on spateo. What is the file you downloaded? Can you let me know, thanks.

**Comment by Zhixuan-Jing** [comment]
The two files are 'SS200000135TL_D1_all_bin1.txt.gz', 'SS200000135IL-D1.ssDNA.tif'; When running, the error occurs

**Comment by Yao-14** [comment]
Are you sure you downloaded these two files from the spateo website? I don't think we are providing these two files now. You can check the website below for the latest sample files. 
https://spateo-release.readthedocs.io/en/latest/autoapi/spateo/sample_data/index.html

**Comment by Zhixuan-Jing** [comment]
> Are you sure you downloaded these two files from the spateo website? I don't think we are providing these two files now. You can check the website below for the latest sample files. https://spateo-release.readthedocs.io/en/latest/autoapi/spateo/sample_data/index.html

Thanks @Yao-14, I have downloaded the latest dataset. However another problem raised: When I was about to load the mouse brain data, an AtributeError occured (shown as follow) 
<img width="464" alt="1668996932507" src="https://user-images.githubusercontent.com/57510261/202946447-837a34e3-95e5-469c-9b96-b55f6f378391.png">
Then I tried other datasets like drosophila, I still cannot load the full data, the problem is also shown below:
<img width="398" alt="1668997278983" src="https://user-images.githubusercontent.com/57510261/202947350-0d764dd8-c168-4897-904d-d719b4cd6a03.png">

Any guidance or help is appreciated

**Comment by dzhu8** [comment]
Hi, @Zhixuan-Jing - thank you for your inquiry, and for catching this error. Please try reinstalling Spateo and downloading the datasets now- hopefully everything should now download smoothly!

Also, as of this moment I don't believe Spateo is availabe on PyPI (referring to the last line in the first screenshot). It can be installed using this command instead: pip install git+https://github.com/aristoteleo/spateo-release

**Comment by Zhixuan-Jing** [comment]
Thanks @dzhu8 for the help - I have reinstalled spateo and dataset, but there is still problem-even though the previous is solved. 
The screenshot is attached below, which are my code and the result. Is there anything wrong in my code?
<img width="769" alt="1669003749250" src="https://user-images.githubusercontent.com/57510261/202963949-0e5b6c43-7d6e-4dfd-90aa-3066b45b7cab.png">

And the result is:
<img width="540" alt="1669003911530" src="https://user-images.githubusercontent.com/57510261/202964040-7ef9e459-57a4-48dd-a3dd-fbf2402371fb.png">

**Comment by dzhu8** [comment]
I think this may be a consequence of how anndata and h5py interact- what version of h5py are you using? Would you mind installing version 3.7.0 and letting us know if this resolves these issues? (`pip install h5py==3.7.0`). If this works we'll put this information onto the Spateo website.

**Comment by Zhixuan-Jing** [comment]
My h5py is 3.7.0 actually, but when I run my code there is still this problem...Here is my default setting on linux, maybe there are some other probblems
[configuration.txt](https://github.com/aristoteleo/spateo-release/files/10053398/configuration.txt)

**Comment by dzhu8** [comment]
Try `pip install anndata==0.8.0`

**Comment by Zhixuan-Jing** [comment]
Thanks @dzhu8  - the problem now get fixed
