### ISSUE TITLE
bioconda recipe

### ISSUE THREAD

**Issue by mjsteinbaugh** [aristoteleo/spateo-release#153]
Hi @Xiaojieqiu,

Congrats on the CZI grant! I wanted to touch base to see if the lab would be open to publishing spateo on bioconda. If so, I'm happy to help build a recipe.

Best,
Mike

**Comment by Xiaojieqiu** [comment]
Thanks Mike! We are also very excited to use the CZI grant to make spateo, dynamo and dynast even more user friendly and functionality rich. If you may happen to know any motivated software engineers who may be interested in this very ambitious endeavor, I would greatly appreciate it if you can introduce them to me!  Thanks for the offering to publish Spateo on bioconda! Please feel free to make a pull request. I am interviewing faculty jobs this week but should be able to review and merge it into the main branch by the end of this week or early next week! 

Thanks,
Xiaojie

**Comment by mjsteinbaugh** [comment]
Hi @Xiaojieqiu , I'm hoping to have some free time over the Christmas break to work on this

**Comment by Xiaojieqiu** [comment]
that's great. looking forward to it. and Merry Christmas ahead. 

Btw, as you may know we have posted our spateo paper to biorxiv and see our tweet about it here for example, https://twitter.com/Xiaojie_Qiu/status/1602354469118906376

**Comment by Xiaojieqiu** [comment]
finish these this week
