### ISSUE TITLE
Type casting from UMI to AGG

### ISSUE THREAD

**Issue by Zhixuan-Jing** [aristoteleo/spateo-release#154]
Hi developers, I am using spateo to do cell segmentation. However, when I read in h5ad file and want to continue, the ConfigurationError occurs and notices "**AnnData provided to `adata` argument must be of `AGG` type, but received `UMI` type**". I do not know how to do the type casting, do you have any suggesstions?

**Comment by dzhu8** [comment]
Hi @Zhixuan-Jing- apologies for the long wait before a response. I think the answer to this is going to depend on the h5ad file you're intending to analyze- for functions that operate on type "AGG" (to my knowledge only segmentation), the input is essentially an image in that the `obs` and `var` correspond to the spatial coordinates, and each element represents the total number of UMIs captured for each X and Y coordinate. 

If you're reading in a more traditional AnnData where `obs` are cells/barcodes and `var` are genes, any functions that ask for "AGG" type AnnData will not be suitable- let me know which function you're calling in case there might be a mistake somewhere!

**Comment by Zhixuan-Jing** [comment]
Thanks for your reply @dzhu8 - I use spateo.read_h5ad() to read the files. More accurately, the file inputs are mousebrain_bin30 and mousebrain_bin60.

**Comment by dzhu8** [comment]
Ah, I just noticed in your original query you mentioned that you want to perform segmentation. mousebrain_bin30 and mousebrain_bin60 have already been processed into cells x genes matrices and are suitable for downstream analysis already- you do not need to perform segmentation on them! 

Thank you for standing by patiently for this response- Spateo is currently still in development and we're a bit preoccupied with the upcoming pre-release and ironing out the kinks in the meantime. We're glad you're using our tool and hope you find it useful for now and in the future!
