### ISSUE TITLE
Add max_num_neighbors to weighted_spatial_graph

### ISSUE THREAD

**Issue by Secretloong** [aristoteleo/spateo-release#155]
I found you had developed the neighbors method with certain radius. But you haven't  provided  the `max_num_neighbors` in function  [`weighted_spatial_graph`](https://github.com/aristoteleo/spateo-release/blob/5efe9ffc026fe48e1e039242436afdac079cfeff/spateo/tools/find_neighbors.py) when call the function `generate_spatial_weights_fixed_radius `.  Could you fix it, so that users could calculate the neighbors with radius more reasonably. THX

**Comment by Secretloong** [comment]
In addition, could you explain how to choose appropriate p and sigma for spatial transcriptome? Why you choose p=0.05, and sigma =100?

**Comment by Secretloong** [comment]
PS, I suggest Spateo should illustrate the `n_neighbors` containing the query spot itself.

**Comment by dzhu8** [comment]
Hi, @Secretloong- thank you for the suggestions and questions on Spateo! I have removed `max_num_neighbors` from `generate_spatial_weights_fixed_radius`- on further examination it was only serving to fix the number of neighbors for each spot. I have also updated the docstring for `weighted_spatial_graph` to hopefully make it more clear what `p` and `sigma` represent; together, the two are used to define a radial threshold past which an imaginary normal distribution with standard deviation `sigma` centered over each spot of interest drops below `p` * max_value. In most cases, fixed neighbors is probably the best way to have some kind of control over the neighborhood composition, but in cases where one might know or have a good idea of the diffusion limit for a soluble factor of interest (under the assumption this will be normally distributed outward from the sending cell), changing `p` and `sigma`  is also an option. 

Finally, what do you mean by illustrate n_neighbors containing the query spot? If it's referring to having the query spot as one of the k nearest neighbors, `construct_nn_graph` can be used to compute an adjacency matrix, where parameter `exclude_self` can be set False to include the query spot as a neighbor.

**Comment by Secretloong** [comment]
Hi Daniel, thanks for your response. I have understood the `generate_spatial_weights_fixed_radius` 's objective. 

For `n_neighbors `, I found it's my misunderstand. There is no self in [`kneighbors`](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.NearestNeighbors.html#sklearn.neighbors.NearestNeighbors.kneighbors). It's different to [`kneighbors_graph`](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.kneighbors_graph.html#sklearn.neighbors.kneighbors_graph).
