### ISSUE TITLE
don't allow registering an already existing cmap

### ISSUE THREAD

**Issue by Secretloong** [aristoteleo/spateo-release#156]
`matplotlib.cm.register_cmap` don't allow registering an already existing cmap unless explicitly asked to
so the function [ `shiftedColorMap`](https://github.com/aristoteleo/spateo-release/blob/6378cbf0a51e887f6cc12a70ffcece8c2ffdf66e/spateo/configuration.py) should not use a fixed name `shiftedcmap`, which caused an error when I repeat the same code `niche_lr_interp.visualize_params` :  
```
ValueError: A colormap named "shiftedcmap" is already registered.
```
I think you could add one code `matplotlib.cm.ColormapRegistry.unregister(plt.colormaps,name='shiftedcmap')` in [ `shiftedColorMap`](https://github.com/aristoteleo/spateo-release/blob/6378cbf0a51e887f6cc12a70ffcece8c2ffdf66e/spateo/configuration.py)

**Comment by Xiaojieqiu** [comment]
Thanks @Secretloong. If I understand correctly, I don't think this will be an issue as long as you avoid run the `shiftedColorMap` multiple times.  

@dzhu8 do you think so?

**Comment by dzhu8** [comment]
This is right, there will be no problems with only running once. However, the suggested line will be included in future development versions of Spateo. For now when using Jupyter you can also manually include the unregister line you have specified here.
