### ISSUE TITLE
How to save the result with different name?

### ISSUE THREAD

**Issue by Zhixuan-Jing** [aristoteleo/spateo-release#157]
Dear developers, When I want to use plotting.imshow(show_save_or_return="all"), I want to put all results into a folder and name them differently. However I cannot do this because there is no option for changing the name. Could you add this function or tell me what to do if there's already one?

**Comment by Zhixuan-Jing** [comment]
Thanks @dzhu8 - I have found this parameter. However I am not qiute clear about the meaning of some keys, like dpi, prefix, could you make it clear in the document or website?

**Comment by dzhu8** [comment]
Yes, I see what you are saying- I will go through and update the function docstrings to better highlight each of these keys. Remind me in a few days if you don't see it update on your end.

**Comment by Zhixuan-Jing** [comment]
Thanks @Yao-14 and @dzhu8 - I have got all results successfully, thank you for the support!
