### ISSUE TITLE
can not downloade the sample dataset

### ISSUE THREAD

**Issue by JingGuo1997** [aristoteleo/spateo-release#158]
Dear Developer, I want to reproduce the slices alignment results, but I think I can not download the sample dataset “E7-9h_bin20_h5ad.zip”
THE ERROR ：

|-----> Downloading data to ./data/E7-9h_bin20_h5ad.zip
https://www.dropbox.com/s/f3c635r4ro4zsmj/bin20_h5ad.zip?dl=1
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
/home/program/conda/anaconda3/envs/spateo/lib/python3.8/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1353             try:
-> 1354                 h.request(req.get_method(), req.selector, req.data, headers,
   1355                           encode_chunked=req.has_header('Transfer-encoding'))

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/http/client.py in request(self, method, url, body, headers, encode_chunked)
   1255         """Send a complete request to the server."""
-> 1256         self._send_request(method, url, body, headers, encode_chunked)
   1257 

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/http/client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1301             body = _encode(body, 'body')
-> 1302         self.endheaders(body, encode_chunked=encode_chunked)
   1303 

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/http/client.py in endheaders(self, message_body, encode_chunked)
   1250             raise CannotSendHeader()
-> 1251         self._send_output(message_body, encode_chunked=encode_chunked)
   1252 

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/http/client.py in _send_output(self, message_body, encode_chunked)
   1010         del self._buffer[:]
-> 1011         self.send(msg)
   1012 

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/http/client.py in send(self, data)
    950             if self.auto_open:
--> 951                 self.connect()
    952             else:

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/http/client.py in connect(self)
   1417 
-> 1418             super().connect()
   1419 

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/http/client.py in connect(self)
    921         """Connect to the host and port specified in __init__."""
--> 922         self.sock = self._create_connection(
    923             (self.host,self.port), self.timeout, self.source_address)

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/socket.py in create_connection(address, timeout, source_address)
    807         try:
--> 808             raise err
    809         finally:

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/socket.py in create_connection(address, timeout, source_address)
    795                 sock.bind(source_address)
--> 796             sock.connect(sa)
    797             # Break explicitly a reference cycle

TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
<ipython-input-8-77e1be10fa8d> in <module>
      1 # cellbin data
----> 2 binning_slices = st.sample_data.drosophila(filename="E7-9h_bin20_h5ad.zip")[3:7]

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/site-packages/spateo/sample_data.py in drosophila(filename, dir_name)
    104         Path(extract_dir).mkdir(parents=True, exist_ok=True)
    105 
--> 106         file_path = download_data(url=url_dict[filename], file_path=filename)
    107         shutil.unpack_archive(file_path, extract_dir)
    108 

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/site-packages/spateo/sample_data.py in download_data(url, file_path, dir_name)
     33         # download the data
     34         print(url)
---> 35         urlretrieve(url, file_path, reporthook=lm.get_main_logger().request_report_hook)
     36 
     37     return file_path

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/urllib/request.py in urlretrieve(url, filename, reporthook, data)
    245     url_type, path = _splittype(url)
    246 
--> 247     with contextlib.closing(urlopen(url, data)) as fp:
    248         headers = fp.info()
    249 

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/urllib/request.py in open(self, fullurl, data, timeout)
    523 
    524         sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> 525         response = self._open(req, data)
    526 
    527         # post-process response

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/urllib/request.py in _open(self, req, data)
    540 
    541         protocol = req.type
--> 542         result = self._call_chain(self.handle_open, protocol, protocol +
    543                                   '_open', req)
    544         if result:

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/urllib/request.py in https_open(self, req)
   1395 
   1396         def https_open(self, req):
-> 1397             return self.do_open(http.client.HTTPSConnection, req,
   1398                 context=self._context, check_hostname=self._check_hostname)
   1399 

/home/program/conda/anaconda3/envs/spateo/lib/python3.8/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1355                           encode_chunked=req.has_header('Transfer-encoding'))
   1356             except OSError as err: # timeout error
-> 1357                 raise URLError(err)
   1358             r = h.getresponse()
   1359         except:

URLError: <urlopen error [Errno 110] Connection timed out>

**Comment by Yao-14** [comment]
Hi @JingGuo1997 ,
Thanks for your question. If you are located in China, I recommend you download the sample data directly from our link(https://www.dropbox.com/s/f3c635r4ro4zsmj/bin20_h5ad.zip?dl=1)  instead of downloading the data through spateo.

**Comment by JingGuo1997** [comment]
> Hi @JingGuo1997 , Thanks for your question. If you are located in China, I recommend you download the sample data directly from our link(https://www.dropbox.com/s/f3c635r4ro4zsmj/bin20_h5ad.zip?dl=1) instead of downloading the data through spateo.

I'm sorry,  i  also cannot open the link.

**Comment by Xiaojieqiu** [comment]
Hi @JingGuo1997 you will need to have a VPN to download the data.

**Comment by Yao-14** [comment]
Hi @JingGuo1997, please check the link below, you can download sample data by the following ways.
https://github.com/aristoteleo/spateo-release/issues/165
