### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by BinyaminKaffe** [aristoteleo/spateo-release#159]
Hi @Xiaojieqiu,

I am experiencing some trouble when trying to install the package. 

I ran pip install git+https://github.com/aristoteleo/spateo-release
and I received an error while getting requirements to build a wheel. 

I will appreciate your help.

I'm providing here the output when I ran 
 pip install git+https://github.com/aristoteleo/spateo-release

Collecting git+https://github.com/aristoteleo/spateo-release
  Cloning https://github.com/aristoteleo/spateo-release to c:\users\97258\appdata\local\temp\pip-req-build-v5om6ld0
  Running command git clone --filter=blob:none --quiet https://github.com/aristoteleo/spateo-release 'C:\Users\97258\AppData\Local\Temp\pip-req-build-v5om6ld0'
  Resolved https://github.com/aristoteleo/spateo-release to commit efd7736d20389ec0b40bb050644fc62812df7c19
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "C:\Users\97258\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\
_in_process.py", line 351, in <module>
          main()
        File "C:\Users\97258\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\
_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\97258\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\
_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\97258\AppData\Local\Temp\pip-build-env-c6kmz_r1\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\97258\AppData\Local\Temp\pip-build-env-c6kmz_r1\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
          super(_BuildMetaLegacyBackend,
        File "C:\Users\97258\AppData\Local\Temp\pip-build-env-c6kmz_r1\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1680: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.

TY

**Comment by Yao-14** [comment]
Hi @BinyaminKaffe,
Are you installing spateo in **Windows**? I recommend you use spateo on **Linux** or **Mac OS**.

**Comment by BinyaminKaffe** [comment]
Hi,

That is correct.

I did however try  also to install on WSL (Mobaxterm), however, I got a different error;

  ERROR: Error [WinError 1920] The file cannot be accessed by the system while executing command git version
ERROR: Could not install packages due to an OSError: [WinError 1920] The file cannot be accessed by the system

I'll appreciate your help.

TY
Binyamin

**Comment by Yao-14** [comment]
emm...Can you connect to the network in WSL? If not, please download spateo in the Windows, then upload spateo to WSL and install it in WSL.

**Comment by Xiaojieqiu** [comment]
spateo is now on PyPi. You can install it via `pip install spateo-release`

**Comment by zhoujoeyyi** [comment]
Hi Xiaojie and the Spateo team,

Congrats on the release of this exciting tool for spatial transcriptomics. 

I tried to install the package using Anaconda on Windows, and ran into error (see screenshot attached).

Any help would be much appreciated!


Thanks,
Joey

![Screenshot 2022-12-13 213116](https://user-images.githubusercontent.com/50421013/207490881-45c9eb55-0262-40d1-a5e9-7d8354de597a.jpg)

**Comment by Yao-14** [comment]
Hi @zhoujoeyyi @BinyaminKaffe , now you guys can try to install the latest version of spateo in **Windows** (note: please do not install via pypi).

**Comment by zhoujoeyyi** [comment]
Hi Jiajun @Yao-14 ,
Thank you so much for the quick response! I will give a try and let you guys know.

Thanks,
Joey

**Comment by zhoujoeyyi** [comment]
Hi Jiajun,
I appreciate your time and effort.
It seems that Windows system still has difficulties installing spateo. 
I avoided using PyPi. And used "pip install git+https://github.com/aristoteleo/spateo-release" to install instead.
Please see screenshot attached.

Thanks,
Joey
![Screenshot 2022-12-14 143533](https://user-images.githubusercontent.com/50421013/207697691-ada53f6d-ac5b-427d-b893-8deb5ff8223a.jpg)

**Comment by Yao-14** [comment]
Hi @zhoujoeyyi , this seems to be because GDAL cannot be installed directly in windows, please check the link carefully.
https://gdal.org/api/python_bindings.html#installation

**Comment by Xiaojieqiu** [comment]
Hi @zhoujoeyyi we were trying hard to enable windows support for Spateo. We thank you reporting the issues and are very happy to help get it through. But it is technically challenging to have a perfect solution in our end too. In the long run, it may be not a perfect idea to use windows for scientific analyses as a lot of scientific toolkits don't have robust windows support.

**Comment by zhoujoeyyi** [comment]
Dear Xiaojie and Jiajun,
Thanks again for the quick response and updates! I will switch to a linux-based system and try it.
Good luck and have fun on the development!

**Comment by kennypavan** [comment]
Greetings! I'm looking forward to trying out your package; however, have also received an error when installing. I'm attempting to install using pip in a virtual Python 3.10 environment on Ubuntu 22.04:
![Screenshot from 2022-12-19 14-29-05](https://user-images.githubusercontent.com/1902873/208539149-7aebad2e-be6f-4f9a-a7d4-f2bcbe780cfb.png)

**Comment by Xiaojieqiu** [comment]
Thanks for your interests in Spateo @kennypavan. Looks like you don't have an HDF5 instalation. This issue may be relevant to you? https://github.com/freqtrade/freqtrade/issues/4162

**Comment by kennypavan** [comment]
Thanks for your quick reply @Xiaojieqiu Unfortunately, I'm still receiving the same error after confirming HDF5 is installed and running correctly. One thing to note is that hdf5 appears to be packaged and run as as h5cc on Ubuntu. When running ```h5cc -showconfig``` the following is return:

```
h5cc -showconfig
	    SUMMARY OF THE HDF5 CONFIGURATION
	    =================================

General Information:
-------------------
                   HDF5 Version: 1.10.7
                  Configured on: Wed, 08 Dec 2021 23:33:27 +0000
                  Configured by: Debian
                    Host system: x86_64-pc-linux-gnu
              Uname information: Debian
                       Byte sex: little-endian
             Installation point: /usr
		    Flavor name: serial

Compiling Options:
------------------
                     Build Mode: production
              Debugging Symbols: no
                        Asserts: no
                      Profiling: no
             Optimization Level: high

Linking Options:
----------------
                      Libraries: static, shared
  Statically Linked Executables: 
                        LDFLAGS: -Wl,-Bsymbolic-functions -flto=auto -Wl,-z,relro
                     H5_LDFLAGS: -Wl,--version-script,$(top_srcdir)/debian/map_serial.ver
                     AM_LDFLAGS: 
                Extra libraries: -lcrypto -lcurl -lpthread -lsz -lz -ldl -lm 
                       Archiver: ar
                       AR_FLAGS: cr
                         Ranlib: x86_64-linux-gnu-ranlib

Languages:
----------
                              C: yes
                     C Compiler: /usr/bin/gcc
                       CPPFLAGS: -Wdate-time -D_FORTIFY_SOURCE=2
                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS: 
                        C Flags: -g -O2 -ffile-prefix-map=$(top_srcdir)=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security
                     H5 C Flags:  -std=c99  -Wall -Wcast-qual -Wconversion -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-include-dirs -Wno-c++-compat -Wno-format-nonliteral -Wshadow -Wundef -Wwrite-strings -pedantic -Wlarger-than=2560 -Wlogical-op -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wsync-nand -Wstrict-overflow=5 -Wno-unsuffixed-float-constants -Wdouble-promotion -Wtrampolines -Wstack-usage=8192 -Wmaybe-uninitialized -Wdate-time -Warray-bounds=2 -Wc99-c11-compat -Wduplicated-cond -Whsa -Wnormalized -Wnull-dereference -Wunused-const-variable -Walloca -Walloc-zero -Wduplicated-branches -Wformat-overflow=2 -Wformat-truncation=1 -Wimplicit-fallthrough=5 -Wrestrict -Wattribute-alias -Wcast-align=strict -Wshift-overflow=2 -Wattribute-alias=2 -Wmissing-profile -fstdarg-opt -s -Wno-aggregate-return -Wno-inline -Wno-missing-format-attribute -Wno-missing-noreturn -Wno-overlength-strings -Wno-jump-misses-init -Wno-suggest-attribute=const -Wno-suggest-attribute=noreturn -Wno-suggest-attribute=pure -Wno-suggest-attribute=format -Wno-suggest-attribute=cold -Wno-suggest-attribute=malloc -O3  -Werror=bad-function-cast -Werror=declaration-after-statement -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=missing-prototypes -Werror=nested-externs -Werror=old-style-definition -Werror=packed -Werror=pointer-sign -Werror=pointer-to-int-cast -Werror=redundant-decls -Werror=strict-prototypes -Werror=switch -Wunused-function -Wunused-variable -Wunused-parameter -Wcast-align -Wunused-but-set-variable -Wformat -Werror=incompatible-pointer-types -Werror=shadow -Wcast-function-type -Wmaybe-uninitialized
                     AM C Flags: 
               Shared C Library: yes
               Static C Library: yes


                        Fortran: yes
               Fortran Compiler: /usr/bin/gfortran
                  Fortran Flags: -g -O2 -ffile-prefix-map=$(top_srcdir)=. -flto=auto -ffat-lto-objects -fstack-protector-strong
               H5 Fortran Flags:  -std=f2008  -Waliasing -Wall -Wcharacter-truncation -Wextra -Wimplicit-interface -Wsurprising -Wunderflow -pedantic -Warray-temporaries -Wintrinsics-std -Wimplicit-procedure -Wreal-q-constant -Wfunction-elimination -Wrealloc-lhs -Wrealloc-lhs-all -Wno-c-binding-type -Wuse-without-only -Winteger-division -Wfrontend-loop-interchange  -s -O3
               AM Fortran Flags: 
         Shared Fortran Library: yes
         Static Fortran Library: yes

                            C++: yes
                   C++ Compiler: /usr/bin/g++
                      C++ Flags: -g -O2 -ffile-prefix-map=$(top_srcdir)=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security
                   H5 C++ Flags:   -Wall -Wcast-qual -Wconversion -Wctor-dtor-privacy -Weffc++ -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-include-dirs -Wno-format-nonliteral -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wreorder -Wshadow -Wsign-promo -Wundef -Wwrite-strings -pedantic -Wlarger-than=2560 -Wlogical-op -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wsync-nand -Wstrict-overflow=5 -Wno-unsuffixed-float-constants -Wdouble-promotion -Wtrampolines -Wstack-usage=8192 -Wmaybe-uninitialized -Wdate-time -Wopenmp-simd -Warray-bounds=2 -Wduplicated-cond -Whsa -Wnormalized -Wnull-dereference -Wunused-const-variable -Walloca -Walloc-zero -Wduplicated-branches -Wformat-overflow=2 -Wformat-truncation=1 -Wimplicit-fallthrough=5 -Wrestrict -Wattribute-alias -Wcast-align=strict -Wshift-overflow=2 -Wattribute-alias=2 -Wmissing-profile -fstdarg-opt -s -O3  -Wcast-align -Wmissing-declarations -Werror=packed -Werror=redundant-decls -Werror=switch -Wunused-but-set-variable -Werror=unused-function -Werror=unused-variable -Wunused-parameter -Werror=shadow
                   AM C++ Flags: 
             Shared C++ Library: yes
             Static C++ Library: yes

                           Java: yes
                  Java Compiler: /usr/bin/java (openjdk 11.0.13 2021-10-19)


Features:
---------
                   Parallel HDF5: no
Parallel Filtered Dataset Writes: no
              Large Parallel I/O: no
              High-level library: yes
                Build HDF5 Tests: yes
                Build HDF5 Tools: yes
                    Threadsafety: yes
             Default API mapping: v18
  With deprecated public symbols: yes
          I/O filters (external): deflate(zlib),szip(encoder)
                             MPE: no
                      Direct VFD: no
                      Mirror VFD: no
              (Read-Only) S3 VFD: yes
            (Read-Only) HDFS VFD: no
                         dmalloc: no
  Packages w/ extra debug output: none
                     API tracing: no
            Using memory checker: no
 Memory allocation sanity checks: no
          Function stack tracing: no
                Use file locking: best-effort
       Strict file format checks: no
    Optimization instrumentation: no
```

I've also attempted to set the HDF5_DIR environment variable as suggested in the error; however, this same error is returned. Additionally, I've attempted to install the python "netCDF4" package via pip. This package appears to use hdf5 as well and did install successfully. 

Perhaps I'm missing something obvious here?

**Comment by Xiaojieqiu** [comment]
I don't have experience with ubutun myself. But have you tried to install spateo using other means except `pip install`? What about also using python 3.7/3.8/3.9? See https://spateo-release.readthedocs.io/en/latest/installation.html

@Yao-14 can you help also since you have a ubuntu system?

**Comment by kennypavan** [comment]
Hi @Xiaojieqiu Modifying the virtual environment to use Python 3.8 appears to have worked along with the ```pip install spateo-release``` command. Thank you for your help.

**Comment by Xiaojieqiu** [comment]
that is great to hear! the HDF5 package and others may don't have robust support for python 3.10 (although github action runs successfully for spateo with python 3.10). 

Please feel free to let us know any other issues you may confront.

**Comment by paulacauhy** [comment]
Hi! I'm running into an error trying to install spateo into MacOS with the M1 chip. I'm getting the error below:

ERROR: Cannot install spateo-release==1.0.0, spateo-release==1.0.1 and spateo-release==1.0.2 because these package versions have conflicting dependencies.

Depending on the python version I install the conflicting dependencies vary. For example, when I had Python 3.9 installed the error message was this:

The conflict is caused by:
    spateo-release 1.0.2 depends on KDEpy>=1.1.0
    spateo-release 1.0.1 depends on KDEpy>=1.1.0
    spateo-release 1.0.0 depends on KDEpy>=1.1.0

But when it was Python 3.12 the error was associated with tensorflow.

How could I fix this?

Thanks a lot!
