### ISSUE TITLE
Spateo_v1_issues Missing Packages

### ISSUE THREAD

**Issue by Xiaojieqiu** [aristoteleo/spateo-release#163]
- [ ] need to install stardist (`pip install stardist`)
- [ ] need to install cdlib (`pip install cdlib`) when running `dyn.tl.louvain` (package issue from dynamo
- [ ] need to instll numpngw when running st.pl.spatial_domains
- [ ] need to install PyMcubes, pymeshfix and pyacvd. 
- [x] add data to figshare
- [x] ensure support of windows

**Comment by Yao-14** [comment]
Hi Xiaojie, now spateo should be able to run normally in Windows. The main reason why it couldn't run in windows before was ngs_tools.

**Comment by Xiaojieqiu** [comment]
Thanks Jiajun! That is great.
