### ISSUE TITLE
Spateo_v1_issues data

### ISSUE THREAD

**Issue by Xiaojieqiu** [aristoteleo/spateo-release#165]
- [x] can we use other data hosting service that are not blocked in China?
- [x] the downloaded data should by default store in the "data" folder

**Comment by Xiaojieqiu** [comment]
can we access https://figshare.com/ there?

**Comment by Yao-14** [comment]
For sure, our sample data has been backed up in figshare at the same time. Now we have two ways to download sample data:

1. Download sample data from dropbox:
```
import spateo as st
# Download sample data from dropbox
adata =  st.sample_data.drosophila(filename="E7-9h_cellbin_tdr_v2.h5ad")
```

2. Download sample data from figshare (friendly to Chinese scientists): 
```
import spateo as st
# Download sample data from dropbox
adata =  st.sample_data.drosophila(filename="E7-9h_cellbin_tdr_v2.h5ad", backup=True)
```

**Comment by Yao-14** [comment]
More information can be found in the link below, which contains download links for all sample data.
https://github.com/aristoteleo/spateo-release/blob/main/spateo/sample_data.py
