### ISSUE TITLE
Spateo_v1_issues 3D reconstruction

### ISSUE THREAD

**Issue by Xiaojieqiu** [aristoteleo/spateo-release#169]
- [x]  error when using `trn` method `samplng_method = "trn"`

**Comment by Yao-14** [comment]
Hi @Xiaojieqiu , I double checked the code and what could be causing this problem. In the end, I determined it was a dynamo version issue (downloading dynamo from **pypi** caused the issue), so please download the latest version of dynamo from **github**.
