### ISSUE TITLE
Confusing number of neighbors in spateo.tools.find_neighbors

### ISSUE THREAD

**Issue by Secretloong** [aristoteleo/spateo-release#172]
The default case in `sklearn.neighbors.NearestNeighbors` is the `kneighbors` without the point with zero distance (non-self neighbors). But  *Spateo* gives the locations twice for `sklearn`: one for fitting the `NearestNeighbors` object, and another for `kneighbors` method. Then, `kneighbors` would output the point itself. the problem is only 8 points could be returned when I set neighbors as 9.

I suggest to delete the variable `locations` at following line (especially line 413 in [find_neighbors.py](https://github.com/aristoteleo/spateo-release/blob/main/spateo/tools/find_neighbors.py))
```
distances, knn = nbrs.kneighbors(locations, n_neighbors=num_neighbors)
```

**Comment by dzhu8** [comment]
This update has now been made in the latest update on Github- thank you for your suggestions!
