### ISSUE TITLE
Spateo for Merfish

### ISSUE THREAD

**Issue by pakiessling** [aristoteleo/spateo-release#175]
Hi there, impressive work.

I am looking forward to trying out spateo on my own data.

Since I work primarily with Merfish data I wanted to make sure, do all of the features work properly with that?

I am asking because there are some differences to Stereoseq, which it seems you are primarily targeting, like not measuring the whole transcriptome and no nanoballs.

Anything major I would need to adjust?

Thank you!

**Comment by Xiaojieqiu** [comment]
@pakiessling Thanks for your interests in our work. Spateo supports all major spatial transcriptomics. You can read the MERFISH data using spateo, we provided a function for this, see: https://spateo-release.readthedocs.io/en/latest/autoapi/spateo/io/merfish/index.html

All downstream analyses should then be mostly the same as MERFISH data. See our demonstration of Spateo for other datasets in the supplementary figure 12/13: https://www.biorxiv.org/content/10.1101/2022.12.07.519417v1.full

**Comment by pakiessling** [comment]
Thank you @Xiaojieqiu. I am asking because I have trouble reading in Merfish data with Spateo.

I am on spateo-release 1.0.2 from pypi and `st.io.merfish.read_merfish()` results in 
`AttributeError: module 'spateo.io' has no attribute 'merfish'`

**Comment by Xiaojieqiu** [comment]
Dear @pakiessling. Can you checkout our example tutorial, which is the basis for the read_merfish() in spateo, on loading the merfish data here: 

https://colab.research.google.com/drive/1-9pLo6872iMLOuOaDVZg1ZXGerj_0xR8

We will fix the bug in spateo shortly

**Comment by pakiessling** [comment]
@Xiaojieqiu perfect, thank you
