### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by QianChwnLyn** [aristoteleo/spateo-release#176]
Hello, when I run 'import spateo', I got 'Illegal instruction: 4'.
I searched for some methods but it didn't help.
<img width="563" alt="image" src="https://user-images.githubusercontent.com/102777768/213108305-bdcd055b-6d87-408a-97bc-05ed05cd10dc.png">

could you help me?

**Comment by Xiaojieqiu** [comment]
thanks for using our tool. can you please tell us how did you install spateo? 

Although I have not studied this closely, you may also find this issue helpful: https://github.com/tensorflow/tensorflow/issues/25822

**Comment by QianChwnLyn** [comment]
Thanks! I download spateo-release from Github. And install by 'python setup.py install'. My python version is 3.9.7. Thanks for your helpful link, I will test this.

**Comment by YAOJ-bioin** [comment]
I meet the similar problem.
I insatll spateo by `pip install spateo-release`  successfully, and through `pip list` , i'm sure i installed the `spateo-release 1.0.2`,;
but when i run 'import spateo as st' ,  it always show `Illegal instruction (core dumped)`
![image](https://github.com/aristoteleo/spateo-release/assets/59159693/74f63e73-b593-477a-a2e7-b726b405c282)
