### ISSUE TITLE
3D reconstruction

### ISSUE THREAD

**Issue by JingGuo1997** [aristoteleo/spateo-release#178]
Hello Spateo developers,

I have downloaded the test data for "three dims models reconstruction" and have completed the "3D reconstruction of original point cloud model" step. However, when I run the "st.pl.three_d_plot" function, the kernel crashes in jupyter. What should I do？

**Comment by Xiaojieqiu** [comment]
We use pyvista to create 3D plots. Some basic questions I have for you is, did you install ipyml that will enable interactive plot in jupyter notebook? see: https://matplotlib.org/ipympl/

Can you also generate pyvista plot in your jupyternotebook environment? See: https://docs.pyvista.org/user-guide/jupyter/index.html

If you provide more detailed description of your bug, we can help yoou further. Also Jiajun @Yao-14 is an expert on this

**Comment by JingGuo1997** [comment]
> 



> We use pyvista to create 3D plots. Some basic questions I have for you is, did you install ipyml that will enable interactive plot in jupyter notebook? see: https://matplotlib.org/ipympl/
> 
> Can you also generate pyvista plot in your jupyternotebook environment? See: https://docs.pyvista.org/user-guide/jupyter/index.html
> 
> If you provide more detailed description of your bug, we can help yoou further. Also Jiajun @Yao-14 is an expert on this

I solved the problem by installing  "xvfb" and setting pv.start_xvfb(). Thank you for your helpful suggestion.
