### ISSUE TITLE
Make sure the L-R database are included in the package

### ISSUE THREAD

**Issue by Xiaojieqiu** [aristoteleo/spateo-release#180]
Spateo comes with reference ligand-receptor pairs databases for several species, including human, mouse, Drosophila, zebrafish and axolotl. Make sure we can access the database when performing ligand-receptor interaction analysis using:

`cci_dict = st.tl.find_cci_two_group(adata, path="/database", species="human", group="cell_type", lr_pair=None, sender_group="cell_type_a", receiver_group=“cell_type_b", top=20, p_value=0.05)`

**Comment by WeipengMO** [comment]
Dear Prof. Qiu @Xiaojieqiu ,

I am trying to obtain the of ligand-receptor pairs databases. Can someone please guide me on how to obtain them?

Thanks!

Bests,
Weipeng

**Comment by WeipengMO** [comment]
Oh, I found it in the repository spateo/tools/database 

#162
