### ISSUE TITLE
module 'dynamo.pp' has no attribute 'normalize_cell_expr_by_size_factors'

### ISSUE THREAD

**Issue by xuansuyang** [aristoteleo/spateo-release#182]
AttributeError: module 'dynamo.pp' has no attribute 'normalize_cell_expr_by_size_factors' when I run the command line dyn.pp.normalize_cell_expr_by_size_factors(adata_bin60, layers="X"), after dir(''dynamo.pp) I found no' normalize_cell_expr_by_size_factors'. There is no problem with dynamo installation, and other functions in Preprocessing can be pulled down, how can I solve it?

**Comment by Sichao25** [comment]
Hi, thanks for reporting the issue. Could you tell me how did you install the dynamo and what version are you currently using?

**Comment by xuansuyang** [comment]
> Hi, thanks for reporting the issue. Could you tell me how did you install the dynamo and what version are you currently using?

git clone https://github.com/aristoteleo/dynamo-release.git
cd dynamo-release/
python setup.py install --user

dynamo version is 1.2.0

**Comment by Sichao25** [comment]
If you use the latest version from GitHub, the `normalize_cell_expr_by_size_factors ` may have been updated to `normalize`. You can check the repo of dynamo for more information. Alternatively, you can use a released version that contains `normalize_cell_expr_by_size_factors`, like dynamo 1.2.0. Let me know if you can't solve the error with this.

**Comment by Xiaojieqiu** [comment]
@Sichao25 let us still support `normalize_cell_expr_by_size_factors` but throw a warning that this function is deprecated and the `normalize` should be used. We will also update spateo later after we release dynamo 1.3.0

**Comment by Xiaojieqiu** [comment]
you may want to fix this bug now because spateo calls this function. We should develop a more robust mechanism for deprecated code in the future

**Comment by xuansuyang** [comment]
> If you use the latest version from GitHub, the `normalize_cell_expr_by_size_factors ` may have been updated to `normalize`. You can check the repo of dynamo for more information. Alternatively, you can use a released version that contains `normalize_cell_expr_by_size_factors`, like dynamo 1.2.0. Let me know if you can't solve the error with this.

Thank you for your answer. I tried to replace the normalize_cell_expr_by_size_factors with normalize and it worked, but I couldn't reproduce the cluster plot in the tutorial.

**Comment by Sichao25** [comment]
May I take a look at your clustering result?

**Comment by xuansuyang** [comment]
Sure. This is my clustering result.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aristoteleo/spateo-release"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月11日(星期四) 上午10:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aristoteleo/spateo-release] module 'dynamo.pp' has no attribute 'normalize_cell_expr_by_size_factors' (Issue #182)





 
May I take a look at your clustering result?

**Comment by Sichao25** [comment]
Hi @xuansuyang, could you try:
```
preprocessor = dyn.pp.Preprocessor()
preprocessor.calc_size_factor(adata)
preprocessor.normalize_by_cells(adata)
preprocessor.norm_method(adata)
```
This should be equal to the `normalize_cell_expr_by_size_factors ` in the earlier version. By the way, I think your results are not displayed correctly here so I can't see the difference.

**Comment by xuansuyang** [comment]
> Hi @xuansuyang, could you try:
> 
> ```
> preprocessor = dyn.pp.Preprocessor()
> preprocessor.calc_size_factor(adata)
> preprocessor.normalize_by_cells(adata)
> preprocessor.norm_method(adata)
> ```
> 
> This should be equal to the `normalize_cell_expr_by_size_factors ` in the earlier version. By the way, I think your results are not displayed correctly here so I can't see the difference.

Thanks.I will retry it later.
