### ISSUE TITLE
使用深度学习方法StarDist进行分割时出现的错误

### ISSUE THREAD

**Issue by YAOJ-bioin** [aristoteleo/spateo-release#193]
出现问题前所有流程都按照教程提示进行，并且非常顺利，直到测试stain_segmentation 这个模块，使用“deeplearning-based-on segmentation”出现问题,如下：
![image](https://github.com/aristoteleo/spateo-release/assets/59159693/f6d8970e-6741-470b-8554-362dae1e43d9)
当我返回使用`pip install stardist` 顺利安装这个包后，重启内核运行改教程。在第一步就出现了问题：
![image](https://github.com/aristoteleo/spateo-release/assets/59159693/1de68e3a-b977-48b0-b77b-da2c129c8ffa)
![image](https://github.com/aristoteleo/spateo-release/assets/59159693/a61f8e4b-1b7e-4fc8-ac03-7ce00648b254)
![image](https://github.com/aristoteleo/spateo-release/assets/59159693/990330f6-92fe-4890-ba21-c6c88232b054)
`AttributeError: module 'tensorflow.keras' has no attribute '__version__'`。 这个问题时因为安装了`stardist`导致的，如果 uninstall stardist 可以顺利import spateo。

请问作者要如何解决这个问题？

**Comment by Sichao25** [comment]
Hi, thanks for reporting the issue. This error message suggests that TensorFlow is not properly installed or loaded. One possible case is that your environment is using two Tensorflow (one existing in the environment, one installed from Stardist). You can try creating a new environment or just uninstalling one of them. Hope this will help you.
