### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by wqy399** [aristoteleo/spateo-release#198]

**Comment by Sichao25** [comment]
Hi @wqy399, thanks for reporting the issue. Could you provide more details on it, like the traceback log?

**Comment by xhli2** [comment]
Hi, I'm installing spateo, and I use the 
`pip install spateo-release`
according to [https://spateo-release.readthedocs.io/en/latest/installation.html](url)
 Unfortunatly the code ended with this error every time.error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2 ,
 cl: 命令行 error D8021 :无效的数值参数“/Wno-unused-variable”
However when I download the zip of code and `pip install .` It shows 'Successfully built spateo-release'
