### ISSUE TITLE
http error when using st.sample_data.drosophila()

### ISSUE THREAD

**Issue by MingLi-929** [aristoteleo/spateo-release#201]
Hi, developers
Thank you for developing such useful software!
I follow your instruction but i come to some bug.
I wanna use the sample data you provide, in https://spateo-release.readthedocs.io/en/latest/tutorials/notebooks/5_tdr/3D%20Reconstruction.html
```
adata = st.sample_data.drosophila(filename="E7-9h_cellbin.h5ad")
```
The first bug came from that there is no file name E7-9h_cellbin.h5ad
![image](https://github.com/aristoteleo/spateo-release/assets/78794151/7f5dcb64-a068-4a37-870e-30446a58e7ea)

And i got it may be is the file
```
adata = st.sample_data.drosophila(filename="E7-9h_cellbin_h5ad.zip")
```

It come with me the second bug
```
File [/biostack/opt/Python-3.8.16/lib/python3.8/urllib/request.py:649](https://vscode-remote+ssh-002dremote-002byulab-005f230-005fgnode01.vscode-resource.vscode-cdn.net/biostack/opt/Python-3.8.16/lib/python3.8/urllib/request.py:649), in HTTPDefaultErrorHandler.http_error_default(self, req, fp, code, msg, hdrs)
    648 def http_error_default(self, req, fp, code, msg, hdrs):
--> 649     raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: HTTP Error 403: Forbidden
```

I check my network, it work normally.

And i check the url provided by 
https://github.com/aristoteleo/spateo-release/blob/5cf055ddd7516104f88ecaa8410a1725eb0fd337/spateo/sample_data.py#L90-L115

The both urls seems having some bugs. https://figshare.com/s/60a8f8b7a350d4fbe23c 
It come with 
![image](https://github.com/aristoteleo/spateo-release/assets/78794151/9762c04a-701f-4b1d-ae22-b56fdfadf8f5)
and i try the url ,it come out with
![image](https://github.com/aristoteleo/spateo-release/assets/78794151/99ab42e9-d5bb-4eec-8f6c-2b5051daaf4e)

May you please help me deal with the sample data bug?
Thanks in advance

**Comment by MingLi-929** [comment]
I try using the backup url
```
adata = st.sample_data.drosophila(filename="E7-9h_cellbin_h5ad.zip",backup=True)
```
It successfully download, but it come out with another bug of ReadError
```
File [/biostack/opt/Python-3.8.16/lib/python3.8/shutil.py:1136](https://vscode-remote+ssh-002dremote-002byulab-005f230-005fgnode01.vscode-resource.vscode-cdn.net/biostack/opt/Python-3.8.16/lib/python3.8/shutil.py:1136), in _unpack_zipfile(filename, extract_dir)
...
-> 1136     raise ReadError("%s is not a zip file" % filename)
   1138 zip = zipfile.ZipFile(filename)
   1139 try:

ReadError: [./data/E7-9h_cellbin_h5ad.zip](https://vscode-remote+ssh-002dremote-002byulab-005f230-005fgnode01.vscode-resource.vscode-cdn.net/biostack/home/liming/3D_reconstruction/spateo/data/E7-9h_cellbin_h5ad.zip) is not a zip file
```

**Comment by Yao-14** [comment]
Hi @MingLi-929 , thank you very much for your recognition of spateo. Sorry, the drosophila  data are temporarily unavailable. The original url link is no longer valid due to our updating of the drosophila data.  We will update the url link after the paper is published.

**Comment by hutaobo** [comment]
Now the paper is published, but the link is still missing:
adata = st.sample_data.drosophila(filename="E7-9h_cellbin.h5ad")
The above command doesn't work.

**Comment by srkl56711** [comment]
I've downloaded the data without specifying a filename.
adata = st.sample_data.drosophila()
