### ISSUE TITLE
st.cs.expand_labels: TerminatedWorkerError

### ISSUE THREAD

**Issue by sunshx-bioinfo** [aristoteleo/spateo-release#202]
Hi, I'm running cell segmentation tutorial for Stain segmentation step by step and i  am encountering the following error at the **st.cs.expand_labels** step: 
`st.cs.expand_labels(
    adata, 'cell_labels', distance=2, out_layer='cell_labels_expanded'
)`

all packages are installed with pip. Has this been encountered before? Looking forward to your replay.

ERROR：
---------------------------------------------------------------------------
TerminatedWorkerError                     Traceback (most recent call last)
Cell In[17], line 1
----> 1 st.cs.expand_labels(
      2     adata, 'cell_labels', distance=2, out_layer='cell_labels_expanded'
      3 )

File /data/sunsx/software/miniconda3/envs/spateo/lib/python3.10/site-packages/spateo/configuration.py:199, in SpateoAdataKeyManager.check_adata_is_type.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    197     else:
    198         raise ConfigurationError(f"AnnData is not AnnData object, but {type(adata)}.")
--> 199 return func(*args, **kwargs)

File /data/sunsx/software/miniconda3/envs/spateo/lib/python3.10/site-packages/spateo/segmentation/label.py:296, in expand_labels(adata, layer, distance, max_area, mask_layer, out_layer)
    294 mask = SKM.select_layer_data(adata, mask_layer) if mask_layer else None
    295 lm.main_info("Expanding labels.")
--> 296 expanded = _expand_labels(labels, distance, max_area, mask=mask)
    297 out_layer = out_layer or SKM.gen_new_layer_key(label_layer, SKM.EXPANDED_SUFFIX)
    298 SKM.set_layer_data(adata, out_layer, expanded)

File /data/sunsx/software/miniconda3/envs/spateo/lib/python3.10/site-packages/spateo/segmentation/label.py:255, in _expand_labels(labels, distance, max_area, mask)
    251     sublabels.append(expanded[sl])
    252     submasks.append(mask[sl])
    253 for i, (_expanded, _new_areas) in zip(
    254     subis,
--> 255     parallel(
    256         delayed(_expand)(
    257             sl, areas, max_area, sm, int(i - 1 >= 0), sl.shape[0] - int(i + step + 1 < labels.shape[0])
    258         )
    259         for i, sl, sm in zip(subis, sublabels, submasks)
    260     ),
    261 ):
    262     expanded[i : i + step] = _expanded
    263     new_areas += _new_areas

File /data/sunsx/software/miniconda3/envs/spateo/lib/python3.10/site-packages/joblib/parallel.py:1952, in Parallel.__call__(self, iterable)
   1946 # The first item from the output is blank, but it makes the interpreter
   1947 # progress until it enters the Try/Except block of the generator and
   1948 # reach the first `yield` statement. This starts the aynchronous
   1949 # dispatch of the tasks to the workers.
   1950 next(output)
-> 1952 return output if self.return_generator else list(output)

File /data/sunsx/software/miniconda3/envs/spateo/lib/python3.10/site-packages/joblib/parallel.py:1595, in Parallel._get_outputs(self, iterator, pre_dispatch)
   1592     yield
   1594     with self._backend.retrieval_context():
-> 1595         yield from self._retrieve()
   1597 except GeneratorExit:
   1598     # The generator has been garbage collected before being fully
   1599     # consumed. This aborts the remaining tasks if possible and warn
   1600     # the user if necessary.
   1601     self._exception = True

File /data/sunsx/software/miniconda3/envs/spateo/lib/python3.10/site-packages/joblib/parallel.py:1699, in Parallel._retrieve(self)
   1692 while self._wait_retrieval():
   1693 
   1694     # If the callback thread of a worker has signaled that its task
   1695     # triggered an exception, or if the retrieval loop has raised an
   1696     # exception (e.g. `GeneratorExit`), exit the loop and surface the
   1697     # worker traceback.
   1698     if self._aborting:
-> 1699         self._raise_error_fast()
   1700         break
   1702     # If the next job is not ready for retrieval yet, we just wait for
   1703     # async callbacks to progress.

File /data/sunsx/software/miniconda3/envs/spateo/lib/python3.10/site-packages/joblib/parallel.py:1734, in Parallel._raise_error_fast(self)
   1730 # If this error job exists, immediatly raise the error by
   1731 # calling get_result. This job might not exists if abort has been
   1732 # called directly or if the generator is gc'ed.
   1733 if error_job is not None:
-> 1734     error_job.get_result(self.timeout)

File /data/sunsx/software/miniconda3/envs/spateo/lib/python3.10/site-packages/joblib/parallel.py:736, in BatchCompletionCallBack.get_result(self, timeout)
    730 backend = self.parallel._backend
    732 if backend.supports_retrieve_callback:
    733     # We assume that the result has already been retrieved by the
    734     # callback thread, and is stored internally. It's just waiting to
    735     # be returned.
--> 736     return self._return_or_raise()
    738 # For other backends, the main thread needs to run the retrieval step.
    739 try:

File /data/sunsx/software/miniconda3/envs/spateo/lib/python3.10/site-packages/joblib/parallel.py:754, in BatchCompletionCallBack._return_or_raise(self)
    752 try:
    753     if self.status == TASK_ERROR:
--> 754         raise self._result
    755     return self._result
    756 finally:

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGABRT(-6)}

**Comment by sunshx-bioinfo** [comment]
Hi, I have solved this problem. When i run it on python=3.9, it works.

**Comment by Sichao25** [comment]
Hi, thanks for reporting the issue. Perhaps there is something wrong with the `joblib` parallel computing in your environment, or it is caused by excessive memory usage like what the message mentions. You can try set `st.config.n_threads = 1` or try another version of `joblib`. Let me know if those suggestions help.
