### ISSUE TITLE
st.io.read_bgi_agg: Padding stain image

### ISSUE THREAD

**Issue by sunshx-bioinfo** [aristoteleo/spateo-release#203]
Hi, When I run **st.io.read_bgi_agg**, I got a message:  **Padding stain image from (17850, 19834) to (26460, 26459) with zeros.**

![1693466485657](https://github.com/aristoteleo/spateo-release/assets/20722414/f857b7f9-9e92-4b63-bb62-f6a22015cbbc)

Does it mean the number of pixels of **JISUI.tif** is less than the number of nanoballs in **D02269B2.txt**?  And then i got cell segmentations, is the result right? If not, how can i rescue my data ?

Looking forward to your replay.

**Comment by Sichao25** [comment]
Hi, thanks for using Spateo. I think padding won't affect your cell segmentations as long as your stain image has the same coordinate system as the read file
