### ISSUE TITLE
TypeError: concat() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by WeipengMO** [aristoteleo/spateo-release#208]
https://github.com/aristoteleo/spateo-release/blob/2c7a546cb42df627366b5cdddcd1cd1af30c77b5/spateo/tools/architype.py#L159

**session_info**

```
Click to view session information
-----
anndata             0.8.0
numpy               1.24.3
pandas              2.1.0
scipy               1.11.2
session_info        1.0.0
spateo              0.0.0
-----
Click to view modules imported as dependencies
-----
IPython             8.15.0
jupyter_client      8.3.1
jupyter_core        5.3.1
-----
Python 3.9.18 (main, Sep 11 2023, 13:41:44) [GCC 11.2.0]
Linux-6.2.0-32-generic-x86_64-with-glibc2.35
-----
Session information updated at 2023-10-11 16:39
```

When I run `adata_bin60.obs = st.tl.archetypes(adata_bin60,m_filter.index,num_clusters=num_clusters)`, it return Error:

```
TypeError: concat() takes 1 positional argument but 2 were given
```

This line should add Positional Arguments axis and set to 1.
```
archetypes = pd.concat((adata.obs, df), axis=1)
```

**Comment by WeipengMO** [comment]
https://github.com/aristoteleo/spateo-release/blob/2c7a546cb42df627366b5cdddcd1cd1af30c77b5/spateo/tools/cci_two_cluster.py#L131

Also, I'm getting the following error message:

```
TypeError: split() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given
```

This line should add `n=2`:
```
cell_pair[["cell_sender", "cell_receiver"]] = cell_pair["cell_pair_name"].str.split(">-<", n=2, expand=True)
```

**Comment by Sichao25** [comment]
Thank you very much for reporting those issues. We will update those in Spateo soon.
