### ISSUE TITLE
Ask for help 

### ISSUE THREAD

**Issue by uush99** [aristoteleo/spateo-release#209]
Dear Nikita,
Thanks for your wonderfull work, and recently, i meet a question,and I didn't get the answer.
I have made a tissue mesh model named "eye_3d_mesh_model" through function ''st.tdr.construct_surface'', and in this function i used one of parameters label : label = "eye". but now i want to change the label based on the mesh data made. and I don't want to use the function "st.tdr.construct_surface" again, because I just want to change the label, and other data of the mesh don't need to change, so what should I do? could I just change the mesh model data, but I dont which function can do this?

my code as belows:

subpopulation_mesh, subpopulation_pc,_ = st.tdr.construct_surface(
pc=embryo_pc,
key_added="tissue",
label='eye',#this i want to change to 'ear'
alpha=1.0,
cs_method="marching_cube",
cs_args={"mc_scale_factor": 1.},
smooth=10000,
scale_factor=1
)
ps: the "subpopulation_mesh" is data of pyvista.core.pointset.PolyData. How can I do for this ? Thanks for your time!

**Comment by Sichao25** [comment]
Hi, thanks for using Spateo. If I understand correctly, you want to change the label information in the output [PolyData](https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.PolyData.html) "subpopulation_mesh". I feel like `.tdr.add_model_labels()` may be the function you are looking for. Alternatively, the label and color can be accessed and directly edited in `.cell_data[key_added]` and `.cell_data[f'{key_added}_rgba']`.

Let me know if this answers your question.

**Comment by uush99** [comment]
Thanks for your answer. I tried the [spateo.tdr.add_model_labels() and .cell_data[key_added] and .cell_data[f'{key_added}_rgba']. but failed. I found that my embryo_pc.cell_data dont have [key_added] or [f'{key_added}_rgba'] .so i dont konw why my data dont have? do you know the reason?

>embryo_pc.cell_data

pyvista DataSetAttributes
Association     : CELL
Active Scalars  : orig_extract_id
Active Vectors  : None
Active Texture  : None
Active Normals  : None
Contains arrays :
    orig_extract_id         int32      (84112,)             SCALARS

photo attatched:
(
![1701086757926](https://github.com/aristoteleo/spateo-release/assets/148845569/05342d2f-3cb3-469f-b05a-9e6dd040827b)
)
Looking forward to your reply!

**Comment by uush99** [comment]
Thank you very much! I checked the code and find the reason. And I have known how to change the labels. the following is what I tried,  the model changed succesfully.

![1701158583444](https://github.com/aristoteleo/spateo-release/assets/148845569/300e5278-91c6-4f14-85b7-970ae2403e62)
 
Thanks again!

**Comment by Yao-14** [comment]
Hi @uush99, Thank you so much for providing such a great solution. Thanks again for using spateo.
