### ISSUE TITLE
请教Spateo绘制AP、DV轴和backbone的问题

### ISSUE THREAD

**Issue by uush99** [aristoteleo/spateo-release#214]
您好，
我可以使用中文请教吗，英文我怕标书不清，谢谢了。
我想请教一下，我使用下面这个函数进行绘制backbone，得到的backbone图形不是曲线，而是一个点，是为什么？
![image](https://github.com/aristoteleo/spateo-release/assets/148845569/5022fb6a-0b68-458a-94c4-c660a254faad)
![image](https://github.com/aristoteleo/spateo-release/assets/148845569/eae7f12a-9c65-44f1-9599-572d8a01c134)
![image](https://github.com/aristoteleo/spateo-release/assets/148845569/39354bc2-cf03-4c45-a187-68d5f613a29d)

另外，请教一下，官网案例上我看到有绘制AP轴和DV轴，不知道能否依据哪个函数可以得到沿AP轴和DV轴显著变化的基因呢？
![image](https://github.com/aristoteleo/spateo-release/assets/148845569/2c758345-868f-4381-aa3b-89a183b43b35)
期待您的回复！感谢！

**Comment by Xiaojieqiu** [comment]
please use English to answer because we need to make sure all users to use get the helps from our response. @Yao-14 can you please help with him?

**Comment by uush99** [comment]
Thank you very much for your work and your response. 
 I'm going to restate my question again in English. Right now, I have solved the first question about why backbone is only a point. And I got the tissue differential genes expression along the backbone using generalized linear regressions. 
But one question about the defination of the degs along the backbone: what are the Degs(Differential genes ) I got along backbone  based on? Are these differential genes distinct from off-backbone? or just compare the differences of all tissue genes between different locations(backbone nodes) along the backbone?

Thanks for your time!

**Comment by Yao-14** [comment]
Hi @uush99 , thanks for using spateo for three-dimensional spatial analysis. There are many reasons for poor backbone reconstruction results, including that your spatial coordinates are too large, the methods or  parameters of reconstruction backbone are not suitable for your data. You can first unify your  spatial coordinates to the micron level or centimeter level, and try other methods to construct backbone (Available methods including  'ElPiGraph',  'SimplePPT' and 'PrinCurve').

**Comment by Yao-14** [comment]
By constructing the backbone, we can get a backbone with labels (labels from 0 to N), so we perform GLM differential expression gene analysis along the backbone, and we can find some genes that are specifically expressed in different regions of the backbone, which can help us understand the different functions in different regions. Especially in samples with segments such as Drosophila embryos.
![image](https://github.com/aristoteleo/spateo-release/assets/89448797/8b51812c-2f71-42dc-8382-bdc3528b3f04)

**Comment by uush99** [comment]
Thank you very much! I understand your reply, I will try it. Thanks again!





> By constructing the backbone, we can get a backbone with labels (labels from 0 to N), so we perform GLM differential expression gene analysis along the backbone, and we can find some genes that are specifically expressed in different regions of the backbone, which can help us understand the different functions in different regions. Especially in samples with segments such as Drosophila embryos. ![image](https://private-user-images.githubusercontent.com/89448797/290392513-8b51812c-2f71-42dc-8382-bdc3528b3f04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjU4MjcsIm5iZiI6MTcwMjUyNTUyNywicGF0aCI6Ii84OTQ0ODc5Ny8yOTAzOTI1MTMtOGI1MTgxMmMtMmY3MS00MmRjLTgzODItYmRjMzUyOGIzZjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAzNDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhM2MwYWY3MGMxYWYxNjBmOTI0YTdhYjU5ZDRhYjJhNWU5ZTg4Yzk2NDEwMTdjMjRlZGY0MWRjMTk1NWE4YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xyXsbJ4qsZqho03kvwwxiwB958P53eiQSo3tLxAJW9E)
