### ISSUE TITLE
ImportError: cannot import name 'UniformGrid' from 'pyvista'

### ISSUE THREAD

**Issue by Biogod2020** [aristoteleo/spateo-release#215]
If you encounter this error, use conda to downgrade the pyvista version to 0.38
`conda install pyvista=0.38`
It seems that "UniformGrid" function was removed from the latest version of pyvista.

**Comment by Yao-14** [comment]
Hi @Biogod2020, thank you very much for raising this issue and providing a solution. In fact, we develop spateo based on version 0.38.0 of pyvista, so this problem may exist. In the future we will update a new version of spateo to support all the latest versions of basic dependency packages.
