### ISSUE TITLE
Are some spateo functions unusable?

### ISSUE THREAD

**Issue by uush99** [aristoteleo/spateo-release#217]
Dear,
I try to do the Morphometric vector field and kinetics, and when I use the function 'st.pl.pairwise_mapping', It shows the function can't exist. Please see the following.
![image](https://github.com/aristoteleo/spateo-release/assets/148845569/5ad8421f-5747-45dd-80ea-5bc86794801f)
So, if any functions cant be used?
Looking forward to your reply!
Thanks.

**Comment by SanL20** [comment]
Happened to me too. Try to check your spateo-release version first. "pip install spateo-release" will only install version 1.0.2, but some functions in the tutorial are only available with the latest version 1.1.0.

**Comment by uush99** [comment]
Thank you very much for your reply. I noted it. And I have tried other function replace it. and I also meet a question about Morphometric vector field and kinetics, and I also asked in github,the question is 'Hi ,could I ask a question about the trajectory model?' if you know, could you please tell me?

Thanks again!

**Comment by Yao-14** [comment]
Hi @uush99,  Thank you very much for using spateo to try morphogenesis analysis, I saw your issue and will answer it in that [link](https://github.com/aristoteleo/spateo-release/issues/218).
