### ISSUE TITLE
Hi ,could I ask a question about the trajectory model?

### ISSUE THREAD

**Issue by uush99** [aristoteleo/spateo-release#218]
Dear Authors,

Thanks for your working, recently, I'm doing the 3D trajectory ,and I want to acquire the result as you showed, like this,
![image](https://github.com/aristoteleo/spateo-release/assets/148845569/9355ba58-774c-45a0-9181-710dda9cfdc5)
But I made this,as follows,
![image](https://github.com/aristoteleo/spateo-release/assets/148845569/3b8e77e8-2ab8-43d4-b9ef-6150862a1500)
Actually, I hope, at least, the arrows indicate a longer length, like your result, but my arrows seem to be the same length, I don't know if it is my code, or through the method you provided in my results can only show this. 
So,do you konw which inflence the result as this?
This is my code.
st.tdr.morphopath(
    adata=mapping_stage1_adata,
    layer="log1p_X",
    vf_key="VecFld_morpho",
    key_added="fate_morpho",
    t_end=20000,
    interpolation_num=50,
    cores=20
)
trajectory_model_x = st.tdr.construct_trajectory(
    adata=mapping_stage1_adata,
    fate_key="fate_morpho",
    n_sampling=1577,
    sampling_method="trn",
    label=mapping_stage1_adata.uns["VecFld_morpho"]["V"][:, 0].flatten(),
    trajectory_color="rainbow",
    tip_color="rainbow",
)
st.pl.three_d_plot(
    model=st.tdr.collect_models([stage1_aligned_mesh, trajectory_model_y_20000]),
    key=["tissue", "trajectory"],
    opacity=[0.2, 1],
    model_style=["surface", "wireframe"],
    model_size=3,
    colormap=["gainsboro", "rainbow"],
    show_legend=False,
    off_screen=False,
    background="black",
    window_size=(512, 512),
)

Please help me, thank you very much.

**Comment by Yao-14** [comment]
Hi @uush99 , please unify the coordinates of your sample to a certain size firstly, such as microns.

**Comment by Yao-14** [comment]
Or you can try to adjust `t_end` in the `st.tdr.morphopath`. The larger the `t_end`, the longer the predicted trajectory, so the longer the trajectory you draw can be.

**Comment by uush99** [comment]
> Hi @uush99 , please unify the coordinates of your sample to a certain size firstly, such as microns.
Thank you very much for your reply! If I understand correctly about you said 'unify the coordinates' ,acturally I have finished to align two stage's data, like this, 
![image](https://github.com/aristoteleo/spateo-release/assets/148845569/39da15cc-9079-4c22-ae24-ddddf5ef7ecf)
As I showed,According to the actual muscle growth, the axis is the same position, and I show the data of the two periods approximately overlap, instead of putting a certain distance between them, as your tutorial showed, and the align-lines's direction I made, if I could think that the align-lines'direction is the cell migrate direction?
