### ISSUE TITLE
AttributeError: module 'spateo.tl' has no attribute 'weighted_spatial_graph'

### ISSUE THREAD

**Issue by xhli2** [aristoteleo/spateo-release#225]
hello,when i run the demo of Cell-cell_interaction,
`weights_graph, distance_graph, adata = st.tl.weighted_spatial_graph(
    adata,
    n_neighbors=10,
)`
with error `AttributeError: module 'spateo.tl' has no attribute 'weighted_spatial_graph'`

**Comment by dzhu8** [comment]
Hi, thank you for using our package, and sorry for the inconvenience! As the package is still in development, some things change quickly. The cell-cell interaction tutorial is out of date and includes references to some deprecated functions, including this one. The tutorials will be updated soon, and remind me periodically if this is not the case.

**Comment by MickYang2333** [comment]
> Hi, thank you for using our package, and sorry for the inconvenience! As the package is still in development, some things change quickly. The cell-cell interaction tutorial is out of date and includes references to some deprecated functions, including this one. The tutorials will be updated soon, and remind me periodically if this is not the case.

Hi, could I know is it still possible for me to conduct cell-cell interaction analysis using this package before the new tutorial release, when weights_graph, distance_graph, adata = st.tl.weighted_spatial_graph( adata, n_neighbors=10, )  no longer be able to use?

**Comment by xhli2** [comment]
> > Hi, thank you for using our package, and sorry for the inconvenience! As the package is still in development, some things change quickly. The cell-cell interaction tutorial is out of date and includes references to some deprecated functions, including this one. The tutorials will be updated soon, and remind me periodically if this is not the case.
> 
> Hi, could I know is it still possible for me to conduct cell-cell interaction analysis using this package before the new tutorial release, when weights_graph, distance_graph, adata = st.tl.weighted_spatial_graph( adata, n_neighbors=10, ) no longer be able to use?

And I find another author and his branch ,finally I find this function ` st.tl.weighted_spatial_graph( adata, n_neighbors=10, ) `

**Comment by MickYang2333** [comment]
> > > Hi, thank you for using our package, and sorry for the inconvenience! As the package is still in development, some things change quickly. The cell-cell interaction tutorial is out of date and includes references to some deprecated functions, including this one. The tutorials will be updated soon, and remind me periodically if this is not the case.
> > 
> > 
> > Hi, could I know is it still possible for me to conduct cell-cell interaction analysis using this package before the new tutorial release, when weights_graph, distance_graph, adata = st.tl.weighted_spatial_graph( adata, n_neighbors=10, ) no longer be able to use?
> 
> And I find another author and his branch ,finally I find this function `st.tl.weighted_spatial_graph( adata, n_neighbors=10, )`

That's great! Which branch did you use? It will be helpful, thank you so much

**Comment by xhli2** [comment]
> > > > Hi, thank you for using our package, and sorry for the inconvenience! As the package is still in development, some things change quickly. The cell-cell interaction tutorial is out of date and includes references to some deprecated functions, including this one. The tutorials will be updated soon, and remind me periodically if this is not the case.
> > > 
> > > 
> > > Hi, could I know is it still possible for me to conduct cell-cell interaction analysis using this package before the new tutorial release, when weights_graph, distance_graph, adata = st.tl.weighted_spatial_graph( adata, n_neighbors=10, ) no longer be able to use?
> > 
> > 
> > And I find another author and his branch ,finally I find this function `st.tl.weighted_spatial_graph( adata, n_neighbors=10, )`
> 
> That's great! Which branch did you use? It will be helpful, thank you so much

Maybe this repo `https://github.com/jiangfuqing/Spateo.git`

**Comment by MickYang2333** [comment]
> > > > > Hi, thank you for using our package, and sorry for the inconvenience! As the package is still in development, some things change quickly. The cell-cell interaction tutorial is out of date and includes references to some deprecated functions, including this one. The tutorials will be updated soon, and remind me periodically if this is not the case.
> > > > 
> > > > 
> > > > Hi, could I know is it still possible for me to conduct cell-cell interaction analysis using this package before the new tutorial release, when weights_graph, distance_graph, adata = st.tl.weighted_spatial_graph( adata, n_neighbors=10, ) no longer be able to use?
> > > 
> > > 
> > > And I find another author and his branch ,finally I find this function `st.tl.weighted_spatial_graph( adata, n_neighbors=10, )`
> > 
> > 
> > That's great! Which branch did you use? It will be helpful, thank you so much
> 
> Maybe this repo `https://github.com/jiangfuqing/Spateo.git`

It finally works! Thank you so much.

**Comment by Xiaojieqiu** [comment]
@dzhu8 can you please fix the notebooks please? it is important to get the latest working notebooks soon

**Comment by dzhu8** [comment]
> hello,when i run the demo of Cell-cell_interaction, `weights_graph, distance_graph, adata = st.tl.weighted_spatial_graph( adata, n_neighbors=10, )` with error `AttributeError: module 'spateo.tl' has no attribute 'weighted_spatial_graph'`

Deepest apologies for the delay! A few updated tutorials have now been uploaded to the tutorials repository: https://github.com/aristoteleo/spateo-tutorials, and should be available on-site soon. Send a message if there are other issues or questions.

**Comment by Xiaojieqiu** [comment]
@dzhu8 did the notebook github page updated? https://spateo-release.readthedocs.io/en/latest/tutorials/index.html
