### ISSUE TITLE
AttributeError: module 'spateo.tl' has no attribute 'models_align_ref'

### ISSUE THREAD

**Issue by weiyouzi321** [aristoteleo/spateo-release#226]
i'm running spateo tutorial and occur attributeerror in [Morphometric vector field and kinetics]1.Alignment of 3D models between adjacent time points,Alignment of 3D models of two stages
which function can replace the spateo.tl.models_align_ref

**Comment by Yao-14** [comment]
Hi @weiyouzi321, all alignment associated functions are in the [spateo.align](https://github.com/aristoteleo/spateo-release/tree/main/spateo/alignment).

**Comment by weiyouzi321** [comment]
> Hi @weiyouzi321, all alignment associated functions are in the [spateo.align](https://github.com/aristoteleo/spateo-release/tree/main/spateo/alignment).

thanks for your guidance!i use st.align.paste_align_ref can pass Alignment steps,looking forward to updated tutorial
