### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'copy' of  stage1_aligned_pc = st.tdr.construct_pc()

### ISSUE THREAD

**Issue by weiyouzi321** [aristoteleo/spateo-release#227]
appreciate your excellent work,but when running [Morphometric vector field and kinetics] 2.morphogenesis vector fields and trajectories:
Generate and check aligned models#Generate aligned point cloud models and mesh models

stage1_aligned_pc = st.tdr.construct_pc(
    adata=mapping_stage1_adata.copy(),
    spatial_key="3d_align_spatial",
    groupby="anno_tissue",
    key_added="tissue",
    colormap={"midgut": "#DC143C"},
)

stage1_aligned_pc  is 'tuple' object without 'copy' attribute however when i try transform stage1_aligned_pc to 'list' object to avoid this error, pc.point is need which leads another error.

![1709000130044](https://github.com/aristoteleo/spateo-release/assets/57709646/9fb18dcd-82e0-43cb-bafa-e248d62a9e4b)
![1709000103527](https://github.com/aristoteleo/spateo-release/assets/57709646/ecfcde35-b555-4a37-9e24-0e90a8adf266)

**Comment by Yao-14** [comment]
Hi @weiyouzi321 , we are very sorry that we have updated the code but not the tutorial yet. We will update the tutorial soon. As you can see, in your code`stage1_aligned_pc[0]` is the pc model you need.

**Comment by weiyouzi321** [comment]
> Hi @weiyouzi321 , we are very sorry that we have updated the code but not the tutorial yet. We will update the tutorial soon. As you can see, in your code`stage1_aligned_pc[0]` is the pc model you need.

thanks for your guidance,it fix the problem.looking forward to updated tutorial!
