### ISSUE TITLE
The boundary_line is empty when I used with st.dd.identify_boundary

### ISSUE THREAD

**Issue by yang050036** [aristoteleo/spateo-release#228]
The boundary_line is empty when I used with `st.dd.identify_boundary`
```python
bdl_img = st.dd.identify_boundary(adata=adata, spatial_key="spatial", cluster_key="leiden_0.2", bin_size=1, source_id=['1', '3'], target_id=['2', '7'])
st.pl.space(adata, color=['boundary_line'], pointsize=0.2, cmap = "Reds")
```
![image](https://github.com/aristoteleo/spateo-release/assets/66415149/93d789b8-4bcf-4ced-af6d-2403ac494284)

What should I do in the next?

**Comment by Sichao25** [comment]
I recommend tuning the parameters, particularly the `source_id` and `target_id`.

**Comment by Sichao25** [comment]
Sure, glad to share my thoughts on this. The algorithm in Spateo is to calculate two contours from the given clusters and get the borderline by masking expanded target contour filling with source contour. This process is mainly implemented using OpenCV/skimage. From my perspective, the most critical step is ensuring that the source and target contours do form a coherent borderline; Under other cases (e.g. selected clusters are far apart), it performs poorly. 

`k_size` refers to the kernel size for `cv2.getStructuringElement`, which defines the unit area for operations like morphological closing. Generally speaking, smaller kernels keep more details, while larger kernels yield smoother results. `min_area` sets the minimal allowable size for `skimage.morphology.remove_small_objects`, which you can view as a kind of noise removal.  `dilate_k_size` specifies the kernel size(thickness) used for dilating or expanding the target contour. 

For more details, you can refer to the OpenCV Morphological Operations tutorial. Always happy to help if you have specific questions on your use case.
