### ISSUE TITLE
cell segmentation cs.score_and_mask_pixels function modulenotfounderror

### ISSUE THREAD

**Issue by vivian-huang** [aristoteleo/spateo-release#235]
Hi,

I am trying to follow the Spateo cell segmentation tutorial, but I am throwing a ModuleNotFoundError for fbgbp at this step for segmentation:

`st.cs.score_and_mask_pixels(
    adata, 'nuclear', k=5, method="EM+BP"
)`

Checking my installed libraries, however, it appears that fbgbp==0.2.1 is already installed.

To try to get around this problem, I directly cloned the fbgbp locally and inserted a path via 

`sys.path.insert(0, "/Users/lab/Downloads/fbgbp/")`
`import fbgbp`

prior to the st.cs.score_and_mask_pixels function, but I am getting a new ModuleNotFoundError: No module named 'fbgbp.binary_belief_propagation'

![image](https://github.com/aristoteleo/spateo-release/assets/48968056/4356a1ba-eeee-4a8e-a7b5-917ed414d313)

Any help with this would be appreciated. Thanks!

**Comment by Xiaojieqiu** [comment]
Hi Vivan, I think you will need to update the fbgbp version to be 0.2.1. 

@YifanLu2000 can you please fix the version issue and dependency issue for spateo?
