### ISSUE TITLE
KeyError: 'Index (0) not understood. ...'

### ISSUE THREAD

**Issue by Mollyx06** [aristoteleo/spateo-release#240]
Hello, I'm trying to build a 3D model using my own spatial slice information, the integration process is as follows, the slices have been aligned
`adata_list_coords = [adata.obsm['align_spatial_3d'] for adata in adata_list]`
`merged_data0 = anndata.concat(adata_list, axis=0)`
`merged_data0.obsm['align_spatial_3d'] = np.concatenate(adata_list_coords, axis=0)`
![image](https://github.com/aristoteleo/spateo-release/assets/71691727/57f0cc29-b003-49b7-95a3-d209cbd4a39d)
But when I try to build the model, the indexing problem is reported as an error
`two_pc, plot_cmap = st.tdr.construct_pc(adata=merged_data0.copy(), spatial_key="align_spatial_3d", groupby=None, key_added="chip_id", colormap="rainbow")`
![image](https://github.com/aristoteleo/spateo-release/assets/71691727/4c15f2ae-c770-4657-9265-d9fa469987bf)
I'd like to know what exactly is meant by indexing here, are the 3D coordinates corresponding to the cells? How do I go about troubleshooting this problem

**Comment by caiquanyou** [comment]
I got the same problem, any ideas?

**Comment by caiquanyou** [comment]
two_pc,= st.tdr.construct_pc(adata=merged_data0.copy(), spatial_key="align_spatial_3d", groupby=None, key_added="chip_id", colormap="rainbow")
return one object would be ok
