### ISSUE TITLE
not enough memory to run construct_surface

### ISSUE THREAD

**Issue by caiquanyou** [aristoteleo/spateo-release#247]
my data contain 580000 cells and I run the construct_surface function and kernal die, any solutions to solve this mem issue .
embryo_mesh, _,_ = st.tdr.construct_surface(pc=embryo_pc, key_added="tissue", alpha=0.6, cs_method="marching_cube", cs_args={"mc_scale_factor": 0.8}, smooth=1000, scale_factor=1.08)

**Comment by Xiaojieqiu** [comment]
Thanks Caiquan. I think the easiest solution is to downsample your data (e.g, to 100, 000). More than half a million cells are a lot. The downsampling generally won't affect your embryo surface. 

@Yao-14 may have additional comments as well

**Comment by caiquanyou** [comment]
Thanks, and may be spateo can develop an parameter or function that automatically downsample the data.
