### ISSUE TITLE
AttributeError: module 'spateo.pl' has no attribute 'spatial_domains'

### ISSUE THREAD

**Issue by Donbbit** [aristoteleo/spateo-release#252]
I did combined visualization of domains and segmented cells using example data, when I run
st.pl.spatial_domains(adata_bin30, bin_size=30, label_key="domain_scc_anno")

I got this error: AttributeError: module 'spateo.pl' has no attribute 'spatial_domains'
​

**Comment by Sichao25** [comment]
Thank you very much for reporting this issue. It seems that the function was accidentally removed in an earlier pull request. We will restore it soon.
