### ISSUE TITLE
bug in tutorial in st.tdr.gp_interpolation

### ISSUE THREAD

**Issue by ustc-fmh** [aristoteleo/spateo-release#286]
when I run code in 
“”“
interpolated_gp_adata = st.tdr.gp_interpolation(source_adata=adata.copy(),
                                                spatial_key="3d_align_spatial",
                                                keys=genes, target_points=np.asarray(voxel.points), device="cpu")
”“”
I got an error is that 
""" RuntimeError: The size of tensor a (3) must match the size of tensor b (512) at non-singleton dimension 1“”“

**Comment by YifanLu2000** [comment]
Hi, thank you very much for your interest in Spateo, and we appreciate you reaching out with this issue—it helps us improve Spateo. Could you provide more detailed information? I’m not entirely sure what went wrong based on the current description.

**Comment by ustc-fmh** [comment]
I have found the reason is that data need normlise and log1p step.

**Comment by YifanLu2000** [comment]
Hi, I wanted to check if your issue has been resolved. I received an email mentioning that the problem was fixed after applying the normalization and log1p steps. Just wanted to confirm with you. Thanks!

**Comment by ustc-fmh** [comment]
You can see my whole code contains normalization and log1p steps. It doesn't work for this problem when i check my result, you can try my whole code first. If it works in your envs, i guess the question maybe exists because of my envs. Thanks!

**Comment by xqzh268** [comment]
您好！我在运行tutorial中高斯过程回归进行三维重建代码时遇到了相同的tenser size不匹配问题，请问如何解决呢

**Comment by YifanLu2000** [comment]
Hi all, thank you for raising this issue! It helped us identify a bug where `keys` could not handle multiple genes but worked fine with a single gene. In the latest version, we have fixed this bug, and the tutorial should now run without any issues.

![image](https://github.com/user-attachments/assets/65469ab1-6d6a-4827-8e57-18c4308fa0b1)

**Comment by xqzh268** [comment]
**Thanks very much** for responding! I replaced the spateo files with new ones, and the problem has been solved ( `pip install spateo-realease` didn't update the files though ). 
Thanks again!

**Comment by YifanLu2000** [comment]
Hi @xqzh268, happy to see this works. Since Spateo is still under development, the package available on PyPI is relatively outdated. One suggestion is to clone our repository via `git clone`, then install it in your desired conda environment using the following command in the cloned directory: 
`pip install -e . `
The `-e` flag stands for "editable," which means you can modify the local files directly. This way, when you update your local Spateo code via `git fetch`, you can use the latest version without reinstalling the package.
