### ISSUE TITLE
Unable to generate 3d plots in a remote (headless) server

### ISSUE THREAD

**Issue by Szym29** [aristoteleo/spateo-release#300]
Hi, 
Thank you for developing Spateo! I am not able to run the following command in the [3D Reconstruction with Pairwise Alignment on Drosophila Data](https://spateo-release.readthedocs.io/en/latest/tutorials/notebooks/3_alignment/5.1%203D%20reconstruction%20on%20Drosophila%20data%20with%20pairwise%20alignment.html) using a headless remote server. 
```python
# show the aligned drosophila in 3D
st.pl.three_d_plot(model=point_cloud,key="tissue",model_style='points',model_size=8, show_axes=True,
    jupyter="static",window_size=(1200, 1200),show_outline=True,outline_kwargs={'show_labels': False, 'outline_width': 3},
    # plotter_filename='./results/Drosophila_8_9_rigid_alignment_reconstruction.html',  # uncomment this for saving the interactive 3D visualization)
```
I also tried `jupyter=none` but still not working.

When I am using the jupyter notebook in the vscode, the kernel will crash when running this command. Here is the log for the error `vtkXOpenGLRenderWindow.:456    ERR| vtkXOpenGLRenderWindow (0x57f25405cad0): bad X server connection. DISPLAY=[0m`
When I am using the terminal, it returns the error `ERROR:root:bad X server connection. DISPLAY=`

Can you help me with this issue?

**Comment by YifanLu2000** [comment]
Hi @Szym29, thank you for raising this issue! Spateo's 3D plotting functions are built upon the [PyVista](https://docs.pyvista.org/) package, and there are certain specifications to consider when running PyVista on a remote server. We recommend reviewing their [tutorials](https://docs.pyvista.org/user-guide/jupyter/trame.html#remote-jupyter-host), particularly for remote Jupyter environments. Also you may check this issue: #273

To get started, you can try the following simple demo code and see whether pyvista works:
```
import pyvista as pv
import numpy as np
pv.start_xvfb()
pv.set_jupyter_backend('trame')

pl = pv.Plotter(notebook=True)
rng = np.random.default_rng(seed=0)
points = rng.random((30, 3))
cloud = pv.wrap(points)
pl.add_mesh(cloud, smooth_shading=True, show_edges=True, render_points_as_spheres=True, point_size=50)

pl.show(jupyter_backend='trame')
```

If everything is set up correctly, you should see an interactive panel like this:

![QQ_1728412866759](https://github.com/user-attachments/assets/06f7642f-e24a-452f-b21d-0c58d07b873b)

Once PyVista is properly installed on your remote server, Spateo's 3D plotting functions should work seamlessly. Here's a preview of the output with demo data from Zhang's dataset:

![QQ_1728413789528](https://github.com/user-attachments/assets/e2090959-1239-43ab-8bd5-beeaa1946616)

Reference: Zhang et al., Molecularly defined and spatially resolved cell atlas of the whole mouse brain.

**Comment by Szym29** [comment]
Hi @YifanLu2000 ,

Thank you for your prompt response. Adding the following chunk of code to the beginning of my jupyter notebook file works. I think it would be great if this part could be indicated somewhere in the manual/docs.  
```python
import pyvista as pv
import numpy as np
pv.start_xvfb()
pv.set_jupyter_backend('trame')
```
Best

**Comment by YifanLu2000** [comment]
Thank you for your suggestion! We will consider creating a tutorial on this.
