### ISSUE TITLE
cell annotations in the embryo dataset

### ISSUE THREAD

**Issue by LeonSong1995** [aristoteleo/spateo-release#303]
Dear authors,

Thank you for your excellent work and for making the embryo data publicly available. We are confused about which annotations to use with the provided embryo data. 

For the E9.5 data, there are 'transf_anno_E95' and 'mapped_celltype'. 
<img width="601" alt="E9 5" src="https://github.com/user-attachments/assets/214b8e62-b03d-4e21-aa5d-268f57ec287a" />

For the E11.5 data, there are 'transf_anno', 'ManualAnnotation', and 'mapped_celltype'
<img width="874" alt="E11 5" src="https://github.com/user-attachments/assets/cb71f462-4fe5-4cb3-9aa3-17c6238b163d" />

Could you please clarify which one we should use? In addition, could you share the spatial domain annotations with us? Thanks! 

Best regards,

**Comment by dzhu8** [comment]
Hi, 

Thank you for the interest in the embryo data! The "mapped_celltype" annotation matches the categorical variable used to color the embryo in our paper. The spatial domain annotations should be found at [this link](https://drive.google.com/file/d/1y_ZoWQgRe67ZJx36VQeAOy4Yg6QdS6Dk/view?usp=sharing). Let me know if there are any further issues.

**Comment by LeonSong1995** [comment]
Thanks for your help!

Best,
Leon

**Comment by LeonSong1995** [comment]
Hi, 

We found that the "mapped_celltype" annotations in `adata.obs` (downloaded from the path provided in the paper) differ from the "mapped_celltype" annotations in the [metadata](https://drive.google.com/file/d/1y_ZoWQgRe67ZJx36VQeAOy4Yg6QdS6Dk/view) you provided 

<img width="873" alt="image" src="https://github.com/user-attachments/assets/4d8ea919-6154-4102-bd67-5bb0feb64fa1" />

Could you please clarify which one we should use? 

Best,
