### ISSUE TITLE
add validators

### ISSUE THREAD

**Issue by Lioscro** [aristoteleo/spateo-release#71]
Add validators for anndatas and layers. Some specific ones that I am thinking are
* Check if an AnnData is of a specific type. For example, if a function requires that an input anndata contain aggregated UMI counts per pixel (`adata.uns['__type'] == 'UMI'`) this validator would be useful.
* Check if a Numpy array is of a specific dtype and/or contains specific values (for example, Numpy array containing cell labels should be integer dtype containing non-negative values).
* Probably others.

**Comment by Xiaojieqiu** [comment]
Hi @Yao-14 , can you help with this? I believe Joseph added this support and we have included type validators for most of our functions. We will need to ensure all necessary functions have this support.
