### ISSUE TITLE
add a few sample datasets to each technology

### ISSUE THREAD

**Issue by Xiaojieqiu** [aristoteleo/spateo-release#90]
Thanks for adding the functions to load data produced from different technologies @Lioscro . I think we will also need to have a few sample datasets from each technology in our package and use those datasets to do a few demonstrations.

**Comment by Xiaojieqiu** [comment]
hey @dzhu8 , have you added those MERFISH, seqFISH, STARmap, seqScope data and others to our sample datasets? Please add those when you are working on the package tutorials

**Comment by dzhu8** [comment]
Yes, those are available in processed form through sample_data along with all of the other datasets used for the paper
